### ISSUE TITLE
"multiple snapshots of same fs not allowed" during "Snapshotting" phase

### ISSUE THREAD

**Issue by fermulator** [psy0rz/zfs_autobackup#20]
Hello! First time user here, first time attempting to use this awesome tool.

Unfortunately ran into an unexpected problem during snapshot.  Can't really figure out what "multiple snapshots of same fs" is referring to.  Per the below, I only see ONE snapshot per filesystem.

NOTE: some of those are ZVOL volumes.

Here's my params for entry:
```
zfs-autobackup --ssh-source fermmy-vms fermmy-server ztank/backup/fermmy-vms \
        --progress \
        --verbose \
        --clear-refreservation \
        --clear-mountpoint
```

Results in:
```
  #### Snapshotting
  [Source] Creating snapshot fermmy-server-20200219212008
! [Source] STDERR > cannot create snapshots : multiple snapshots of same fs not allowed
! [Source] STDERR > no snapshots were created
Traceback (most recent call last):
  File "/usr/local/bin/zfs-autobackup", line 1470, in <module>
    sys.exit(zfs_autobackup.run())
  File "/usr/local/bin/zfs-autobackup", line 1413, in run
    source_node.consistent_snapshot(source_datasets, source_node.new_snapshotname(), allow_empty=self.args.allow_empty)
  File "/usr/local/bin/zfs-autobackup", line 1252, in consistent_snapshot
    self.run(cmd, readonly=False)
  File "/usr/local/bin/zfs-autobackup", line 471, in run
    raise(subprocess.CalledProcessError(p.returncode, encoded_cmd))
```
I did a quick find-replace `, ` with `\n` for readability:
```
subprocess.CalledProcessError: Command '[b'ssh'
b'fermmy-vms'
b"'zfs'"
b"'snapshot'"
b"'bpool@fermmy-server-20200219212008'"
b"'bpool/BOOT@fermmy-server-20200219212008'"
b"'bpool/BOOT/ubuntu@fermmy-server-20200219212008'"
b"'rpool@fermmy-server-20200219212008'"
b"'rpool/ROOT@fermmy-server-20200219212008'"
b"'rpool/ROOT/ubuntu@fermmy-server-20200219212008'"
b"'rpool/home@fermmy-server-20200219212008'"
b"'rpool/home/fermulator@fermmy-server-20200219212008'"
b"'rpool/home/root@fermmy-server-20200219212008'"
b"'rpool/tmp@fermmy-server-20200219212008'"
b"'rpool/usr@fermmy-server-20200219212008'"
b"'rpool/usr/local@fermmy-server-20200219212008'"
b"'rpool/var@fermmy-server-20200219212008'"
b"'rpool/var/lib@fermmy-server-20200219212008'"
b"'rpool/var/log@fermmy-server-20200219212008'"
b"'rpool/var/spool@fermmy-server-20200219212008'"
b"'zstorage@fermmy-server-20200219212008'"
b"'zstorage/nfs@fermmy-server-20200219212008'"
b"'zstorage/nfs/fermmy-boinc0@fermmy-server-20200219212008'"
b"'zstorage/nfs/fermmy-boinc0/disk0@fermmy-server-20200219212008'"
b"'zstorage/vms@fermmy-server-20200219212008'"
b"'zstorage/vms/archived@fermmy-server-20200219212008'"
b"'zstorage/vms/git@fermmy-server-20200219212008'"
b"'zstorage/vms/git/disk0@fermmy-server-20200219212008'"
b"'zstorage/vms/git/disk1@fermmy-server-20200219212008'"
b"'zstorage/vms/home-assistant@fermmy-server-20200219212008'"
b"'zstorage/vms/home-assistant/disk0@fermmy-server-20200219212008'"
b"'zstorage/vms/house@fermmy-server-20200219212008'"
b"'zstorage/vms/house/disk0@fermmy-server-20200219212008'"
b"'zstorage/vms/nextcloud@fermmy-server-20200219212008'"
b"'zstorage/vms/nextcloud/disk0@fermmy-server-20200219212008'"
b"'zstorage/vms/services@fermmy-server-20200219212008'"
b"'zstorage/vms/services/disk0@fermmy-server-20200219212008'"
b"'zstorage/vms/services/disk1@fermmy-server-20200219212008'"
b"'zstorage/vms/foo@fermmy-server-20200219212008'"
b"'zstorage/vms/foo/disk0@fermmy-server-20200219212008'"
b"'zstorage/vms/bar@fermmy-server-20200219212008'"
b"'zstorage/vms/bar/disk0@fermmy-server-20200219212008'"]' returned non-zero exit status 1.
```

**Comment by psy0rz** [comment]
This is an actual bug cause by a zfs feature: It tries to make a consistent snapshot across multieple pools, which is not allowed.

Try using different backup names for rpool and storage, and use 2 backup jobs.

However, i'll mark this as a bug and change zfs-autobackup so it will detect this and use a consitent snapshot PER pool instead of globally.

**Comment by psy0rz** [comment]
fixed it, you can download it here: https://raw.githubusercontent.com/psy0rz/zfs_autobackup/master/bin/zfs-autobackup or wait until i release it via pip.
